name: GitHub Actions Demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: config AWS credentials
        # You may pin to the exact commit or the version.
        # uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # AWS Access Key ID. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          # AWS Secret Access Key. This input is required if running in the GitHub hosted environment. It is optional if running in a self-hosted environment that already has AWS credentials, for example on an EC2 instance.
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          # AWS Session Token
          aws-region: ap-southeast-1
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Maven Action
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: |
          cd cicd-2/
          mvn package docker:build
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 457551501671.dkr.ecr.ap-southeast-1.amazonaws.com
          docker tag vu.nguyen/cicd-2:latest 457551501671.dkr.ecr.ap-southeast-1.amazonaws.com/vu.nguyen/cicd-test:latest
          docker push 457551501671.dkr.ecr.ap-southeast-1.amazonaws.com/vu.nguyen/cicd-test:latest
#
#  Deploy-docker:
#    runs-on: ubuntu-latest
#    needs:
#      - Build
#    steps:
#      -
