name: GitHub Actions Demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Maven Action
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: mvn -V package docker:build
#
#  Deploy-docker:
#    runs-on: ubuntu-latest
#    needs:
#      - Build
#    steps:
#      -