name: deploy-prod
on:
  workflow_run:
    workflows: [build-deploy]
    types: [completed]
    branches: [main]
jobs:
  extract-number:
    runs-on: ubuntu-latest
    environment: prod
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value

  deploy-prod-sin:
    runs-on: ubuntu-latest
    environment: prod
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    steps:
      - run: echo 'Deploying prod. Update'
